### ISSUE TITLE
KeyError: 'phenotypes' in 'compute_phenotype_diagram'

### ISSUE THREAD

**Issue by etonello** [hklarner/pyboolnet#104]
When running the tutorial ```07_commitment.py```, a KeyError is raised:

```
Traceback (most recent call last):
  File "pyboolnet/tutorials/07_commitment.py", line 12, in <module>
    diagram = compute_phenotype_diagram(attractors)
  File ".local/lib/python3.9/site-packages/pyboolnet/phenotypes.py", line 168, in compute_phenotype_diagram
    flags = [[0, 1]] * len(phenotypes["phenotypes"])
KeyError: 'phenotypes'
```

The system is Debian 11 with python version 3.9.

**Comment by hklarner** [comment]
Thanks for posting. I will find time to look at it next week.

**Comment by hklarner** [comment]
Ok, can reproduce the error.

**Comment by hklarner** [comment]
I am not sure how this script ever worked, since it is passing the attractors object to the `compute_phenotype_diagram` function, see: https://github.com/hklarner/pyboolnet/blob/8c9d5492433af3f8efab6e4cd9925092a5bfce7c/tutorials/07_commitment.py#L12

Also, the markers that define the phenotypes are not specified.

I would like to change the tutorial to this code. I can't remember the model, I just picked two markers randomly. Can you check whether it runs for you?

```python
from pyboolnet.attractors import compute_attractors
from pyboolnet.phenotypes import phenotype_diagram2image, compute_phenotype_diagram, create_phenotypes_piechart
from pyboolnet.phenotypes import compute_phenotypes
from pyboolnet.repository import get_primes


if __name__ == "__main__":
    primes = get_primes("tournier_apoptosis")
    attractors = compute_attractors(primes=primes, update="asynchronous")
    phenotypes = compute_phenotypes(attractors=attractors, markers=["T2", "TNF"])
    diagram = compute_phenotype_diagram(phenotypes=phenotypes)

    phenotype_diagram2image(diagram=diagram, fname_image="commitment_diagram.pdf")
    create_phenotypes_piechart(diagram=diagram, fname_image="commitment_piechart.pdf")
```

**Comment by etonello** [comment]
It works, thanks.
I have two related questions. To generate the commitment diagram for all attractors, would you use the same code, with all variables as markers?
Is there simple way to create phenotypes from attractors by grouping them "manually", without using ```compute_phenotypes```?
Thanks!

**Comment by hklarner** [comment]
> To generate the commitment diagram for all attractors, would you use the same code, with all variables as markers?

There are two tutorial scripts:
- `07_commitment.py` for commitment sets, and
- `08_phenotypes.py` for phenotypes

I just realized that the above code belongs into the phenotypes file. And the correct code for the commitment diagram is this:

```python
from pyboolnet.attractors import compute_attractors
from pyboolnet.commitment_diagrams import compute_commitment_diagram, create_commitment_piechart
from pyboolnet.repository import get_primes


if __name__ == "__main__":
    primes = get_primes("tournier_apoptosis")
    attractors = compute_attractors(primes=primes, update="asynchronous")

    diagram = compute_commitment_diagram(attractors=attractors, fname_image="commitment_diagram.pdf")
    create_commitment_piechart(diagram=diagram, fname_image="commitment_piechart.pdf")
```

So to create the commitment diagram, use the function `compute_commitment_diagram`.

**Comment by hklarner** [comment]
> Is there simple way to create phenotypes from attractors by grouping them "manually", without using compute_phenotypes?

Currently, a phenotype object is tightly linked to subspaces (i.e. markers) and you cannot manually group attractors into phenotypes.

**Comment by hklarner** [comment]
> Is there simple way to create phenotypes from attractors by grouping them "manually", without using compute_phenotypes?

I just looked at the source of `compute_phenotypes` and I can not judge how difficult it would be to extend it with the feature "manual grouping of phenotypes". Technically you would have to create a phenotype object (called `pheno` in the source) for a list of attractors. But there are three properties that relate directly to markers: `activated_markers`, `inhibited_markers`, `oscillating_markers`. Not sure if they can easily be ignored / extended with defaults so that a manual phenotypes object still works with the `create_phenotype_diagram` and `_piechart` functions.

If you are thinking along those lines you can open a discussion with ideas about this extension.

- https://github.com/hklarner/pyboolnet/discussions

**Comment by etonello** [comment]
> If you are thinking along those lines you can open a discussion with ideas about this extension.
> 
>     * https://github.com/hklarner/pyboolnet/discussions

Ok, thank you. For now with the tutorials fixed the issue is solved.
