### ISSUE TITLE
Basins example in the documentation

### ISSUE THREAD

**Issue by RSchwieger** [hklarner/PyBoolNet#20]
The basins example on p. 48:
```
primes = Repository.get_primes("arellano_rootstem")
diagram = Commitment.compute_diagram(primes, "asynchronous", FnameImage= "commitment.pdf")
```
gives me the error:

```
Traceback (most recent call last):
  ...
diagram = Commitment.compute_diagram(primes, FnameImage="commitment.pdf")
  File "/usr/local/lib/python3.6/dist-packages/PyBoolNet/Commitment.py", line 59, in compute_diagram
    Primes = AttrJson["primes"]
KeyError: 'primes'
```

**Comment by hklarner** [comment]
Hi Robert,
the main section of the manual is unfortunately outdated in some parts. This is an example. The signature of `Commitment.compute_diagram(..)` has changed. The first parameter is now the attractors object rather than the primes and update. Take a look at the reference of `Commitment.compute_diagram(..)`.

example:
```
>>> attrs = Attractors.compute_json(primes, "asynchronous")
>>> diagram = Commitment.compute_diagram(attrs, FnameImage="commitment.pdf")
```

will be fixed in next version 2.2.5
