### ISSUE TITLE
Visualizing Trap Spaces

### ISSUE THREAD

**Issue by hklarner** [hklarner/PyBoolNet#22]
I was wondering whether there is a way of visualising
trap spaces in PyBoolNet. What I have in mind is something like in the
picture attached. I could not find anything, but maybe you know if it
would be feasible/difficult/easy to implement such a graph in PyBoolNet?
![trap_spaces](https://user-images.githubusercontent.com/1685557/47509998-83475c80-d877-11e8-8c81-30cadd8d32d7.png)

**Comment by jcrozum** [comment]
I realize this post is quite old, but I just now stumbled across it while looking for something else and I thought I'd chime in since I've been working on this sort of thing for a while and can report some success.

If you'll forgive a bit of shameless self-promotion, our library PyStableMotifs (https://github.com/jcrozum/PyStableMotifs) implements something very similar to this graph, which we call a "succession diagram".

We build the diagram recursively (depth first) using PyBoolNet's ASPSolver module to find maximal trap spaces, which we then percolate. At each step in the recursion, we run a series of tests that help us quickly determine the completeness, faithfulness, and univocality of the resulting collection of trap sets. We use some network reduction methods and new theorems about how they interact with trap spaces to speed things along and to let us handle larger networks. The full details are in our recent Science Advances paper (Rozum et al. 2021, https://advances.sciencemag.org/content/7/29/eabf8124), and of course I'm happy to discuss it further if you're interested.

We also have options for condensing these diagrams and several algorithms that use them for attractor control. The control part is not covered in the Sci Adv paper; it's the subject of a manuscript we submitted to Bioinformatics about a week ago.

**Comment by hklarner** [comment]
Interesting. Thanks for sharing this!

I'd love to hear more about this work.

Since the health crisis we've had several seminars via zoom. If you have slides and would like to present and discuss your approach I'd like to offer you a slot at our group seminar at Freie Universität Berlin.

Send me an email, if you're interested: hannes.klarner@fu-berlin.de

BTW: I am currently refactoring PyBoolNet to pyboolnet. It will mainly consist of changing the case of all parameters and modules to conform with standard python. Since you're importing PBN this would also affect you, but should only involve some search and replace work.

**Comment by jcrozum** [comment]
Thanks, I'd love to present some slides at your group seminar! I'll send a separate email to work out the details.

I did recall that you were planning to refactor the code -- that was the "something else" I mentioned I was looking for (I did find your discussion post about it, by the way). Thanks for the reminder though!
