### ISSUE TITLE
What is the algorithm that uses the function compute_json ()?

### ISSUE THREAD

**Issue by crptcusco** [hklarner/PyBoolNet#25]
Maybe I did not read the manual well, but I could not find the algorithm or paper on which the function `compute_json() ` is based, it says that it is a high performance technique, for inputs greater than Tarjan's algorithm, but I did not find anything else.

**Comment by hklarner** [comment]
i will get back to you asap

**Comment by hklarner** [comment]
@crptcusco sorry, very busy. Will get back to you asap! In the mean time, the main two publication for our model checking based computation of attractors can be found here:
* https://www.frontiersin.org/articles/10.3389/fbioe.2015.00130/full
* https://link.springer.com/article/10.1007/s11047-015-9520-7

**Comment by hklarner** [comment]
@crptcusco sorry for the late reply. `compute_json()` is a bad name on its own, maybe it helps if you put add the module name: `Attractors.comute_json(..)`. The computation of attractors and their properties quickly becomes computationally expensive. Typically and with the right technology, computing steady states is cheap and fast because it can be translated into a SAT problem and there are powerful SAT solvers available.
Asynchronous attractors on the other hand are harder to compute as they potentially cover large parts of the state space. Even worse, confirming that a given set of states is in deed an attractor requires checking that
1) the states are strongly connected via the transition relation
2) the states are closed under the transition relation

The function `compute_json()` computes all minimal trap spaces (are you familiar with the concept? They generalize steady states)  and tests whether they describe all attractors of the system. This is characterized by three properties:
- completeness
- univocality
- faithfulness

Again, not the best choice of naming here. Basically, if the answer is "yes" in each case then you have a simple Boolean network. Its attractors are easy to understand. If the answer is "no" somewhere then there are problems. Please check the papers I mentioned above if you want to learn more. Or ask specific questions so I can elaborate.
Since computing these properties is expensive this function lets you save and load attractor information for a given Boolean network.

Hope this helps!?

**Comment by hklarner** [comment]
Here is a link to an example:
https://github.com/hklarner/PyBoolNet/blob/master/PyBoolNet/Repository/dahlhaus_neuroplastoma/dahlhaus_neuroplastoma_attrs_async.json

Each object in the attractors array represents and describes one attractor. Some are steady states (`"is_steady": True`) and some are so-called cyclic attractors with more than one state (`"is_steady": False`).
Cyclic attractors are described by minimal trap spaces where some Boolean variables are forever fixed (`"mintrapspace"`) and the remaining variables will oscillate forever. `"state"` gives you a state that belongs to the attractor, an "internal state". You can think of it as a representative of the attractor. If you initialize the system with this state you are inside the attractor.

As you can see this network is simple, as all attractors are univocal and faithful and the set of attractors is complete.

**Comment by hklarner** [comment]
I'll leave this open, as other users might find this helpful.
