### ISSUE TITLE
Problem with module installation

### ISSUE THREAD

**Issue by Domeniko70** [hklarner/PyBoolNet#39]
Hello Prof. Klarner
I would like to use the PyBoolNet module for my gene regulation network but I haven't been able to install the module in my system so far. Using the "pip install git + https: //github.com/hklarner/PyBoolNet" command on 'Anaconda' I get no results. On Google Colab the message is the following: "ERROR: Could not find a version that satisfies the requirement PyBoolNet (from version: none). By typing" pip install git + https: //github.com/hklarner/PyBoolNet@2.2.9 "I get the response from the system" ssh: Could not resolve hostname http: Name or service not know fatal: Could not read from remote repository.
Thank you for you help

**Comment by hklarner** [comment]
I don't use Anaconda and I don't use Colab, so I can't really help you here.

@aurelien-naldi @carissableker Do you know something here?

@Domeniko70 Can you confirm that a local install works? What OS are you on? On Linux, the following works for me from the terminal:

```
~$ pip3 install git+https://github.com/hklarner/PyBoolNet
...
Successfully installed PyBoolNet-2.2.9 networkx-2.4
~$ python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27)
>>> import PyBoolNet
>>> PyBoolNet.Tests.run()
...
Ran 100 tests in 6.480s

OK
>>>
```

**Comment by carissableker** [comment]
## Anaconda:

I was able to install it both in Linux (in a clean miniconda environment) and in Windows (at the Anaconda prompt) using both 

`pip install git+https://github.com/hklarner/PyBoolNet`

and 

`pip install git+https://github.com/hklarner/PyBoolNet@2.2.9`

I find it hard to believe Anaconda gave no results (not even an error message?). If it was typed at the prompt as you put in your comment, then it would not work anyway (due to spaces that should not be there). 

## Colab
I don't either use colab, but a simple test seemed to work fine as well (apart from expected libreadline.so.6 errors):
![image](https://user-images.githubusercontent.com/26261557/91980357-6c051000-ed27-11ea-97b0-4fbade8b4012.png)

**Comment by aurelien-naldi** [comment]
I can't say anything about colab.

Using anaconda should not change the behaviour of pip: it only provides a separate python installation.
However, installing though pip inside a conda environment should be avoided when proper conda packages are available.
The colomoto channel now contains a pyboolnet package, you should be able to install it with:

conda install -c colomoto -c potassco pyboolnet

**Comment by Domeniko70** [comment]
I use windows10. I just deleted and reinstalled Anaconda on my pc. After this I managed to install the package with 'Anaconda prompt' and import the library with spyder ('import PyBoolNet'), but at the command '>>> PyBoolNet.Tests.run ()' I get the following result:  
                                    Ran 100 tests in 15.320s
                                    FAILED (errors=14)
Thank you

**Comment by Domeniko70** [comment]
...and this is the result after I typed on the Anaconda Prompt "conda install -c colomoto -c potassco pyboolnet"
![fig 2](https://user-images.githubusercontent.com/70635035/92007131-d9279e00-ed45-11ea-9b77-7d0923695241.PNG)

**Comment by carissableker** [comment]
Not near a computer now, but I think the error you get in the run tests are only for Numsv (see issue 23) - depending on what you are doing, you may get away with using PyBoolNet as is.
