### ISSUE TITLE
Ouput Nodes are not clustered together

### ISSUE THREAD

**Issue by valentin-noske** [hklarner/PyBoolNet#74]
I tried to run this code example out of the PyBoolNet tutorial.
The input, constant and output nodes should get clustered together in the interaction graph but however this only works for the input nodes.
In this code example I used the "arellano rootstem" network that is part of the repo but it is not working for other networks as well.
I have a ubuntu 20.04 distro and I am using python 3.8.

```
import PyBoolNet 
import PyBoolNet.InteractionGraphs as IGs

primes = PyBoolNet.Repository.get_primes("arellano_rootstem")
igraph = IGs.primes2igraph(primes)
IGs.add_style_inputs(igraph)
IGs.add_style_constants(igraph)
IGs.add_style_outputs(igraph)
IGs.igraph2image(igraph, "igraph.pdf")
```

**Comment by valentin-noske** [comment]
[igraph.pdf](https://github.com/hklarner/PyBoolNet/files/6790899/igraph.pdf)

**Comment by hklarner** [comment]
Very good, that's a bug!

## The bug
What's happening is that we bumped the version of networkx to 2.5 and the DiGraph method `digraph.successors` is now a generator as opposed to a list in networkx 1.

Hence the output detection in `InteractionGraphs.add_style_outputs`

https://github.com/hklarner/PyBoolNet/blob/bbb538068a470a593ebe60ede7ce38c900ad7141/PyBoolNet/InteractionGraphs.py#L451

fails because `IGraph.successors(x)` is now a generator and evaluates to _True_ (as opposed to the empty list).

This bug also affects `PrimeImplicants.find_outputs`:
https://github.com/hklarner/PyBoolNet/blob/bbb538068a470a593ebe60ede7ce38c900ad7141/PyBoolNet/PrimeImplicants.py#L116-L119

- note that the two conditions for a node to be output are different!

## Fix suggestion 1
I suggest to fix `InteractionGraphs.add_style_outputs` with
```
outputs = []
for x in IGraph.nodes():
    successors = list(IGraph.successors(x))
    if not successors or successors == [x]:
        outputs.append(x)
```

And `PrimeImplicants.find_outputs` with
```
outputs = [x for x in igraph if not list(igraph.successors(x))]
```


## Fix suggestion 2
I am not sure why there should be two definitions of output.
Alternatively, fix `InteractionGraphs.add_style_outputs` by the same statement
```
outputs = [x for x in igraph if not list(igraph.successors(x))]
```


What fix makes more sense to you?

Do you want to send a PR to develop?

**Comment by hklarner** [comment]
btw I think the hierarchical layout with `dot` is much clearer (top to bottom) than the default force directed layout.
```
IGs.igraph2image(igraph, "igraph.pdf", LayoutEngine="dot")
```

**Comment by valentin-noske** [comment]
The "dot"-LayoutEngine looks much better, thank you! I think I can make these little changes in both functions, your suggestion 2 makes more sense to me.

**Comment by hklarner** [comment]
you should be able to install the fixed version with
```
pip3 install git+https://github.com/hklarner/PyBoolNet@develop
```

I'll make a release asap.
